# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Coordinates-UTM-XS
version:      0.01
version_from: lib/Geo/Coordinates/UTM/XS.pm
installdirs:  site
requires:
    Geo::Coordinates::UTM:         0.05
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
