--- #YAML:1.0
name:                Geo-Coordinates-UTM-XS
version:             0.03
abstract:            C/XS reimplementation of Geo::Coordinates::UTM
license:             ~
author:              
    - Salvador Fandino <sfandino@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Geo::Coordinates::UTM:         0.05
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
